{
 "title": "System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "mem_mapped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Mapped" }
   ]
  },
  {
   "title": "Node disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_bytes_written{device=\"sda1\", instance=\"10.0.55.14:9100\", job=\"node\"}"
    },
    {
     "expr": "node_disk_bytes_written{device=\"sda1\", instance=\"localhost:9100\", job=\"node\"}"
    }
   ]
  },
  {
   "title": "cpu_client",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu{cpu=\"cpu0\", instance=\"10.0.55.14:9100\", job=\"node\", mode=\"iowait\"}"
    }
   ]
  },
  {
   "title": "CPU_server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu{cpu=\"cpu0\", instance=\"localhost:9100\", job=\"node\", mode=\"iowait\"}"
    },
    {
     "expr": "node_cpu{cpu=\"cpu1\", instance=\"localhost:9100\", job=\"node\", mode=\"iowait\"}"
    }
   ]
  }
 ]
}